name: upstorage_desktop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  intl: ^0.17.0
  adaptive_theme: ^2.3.0
  flutter_svg: ^1.0.3
  flutter_bloc: ^8.0.1
  formz: ^0.4.1
  equatable: ^2.0.3
  dio: ^4.0.4
  get_it: ^7.2.0
  injectable: ^1.5.3
  persistent_bottom_nav_bar: ^4.0.2
  permission_handler: ^9.1.0
  scrollable_positioned_list: ^0.2.3
  hive: ^2.0.5
  path_provider: ^2.0.9
  desktop_window: ^0.4.0
  shared_preferences: ^2.0.13
  shared_preferences_platform_interface: ^2.0.0
  file_picker: ^4.4.0
  image_picker: ^0.8.4+9
  percent_indicator: ^4.0.0
  connectivity: ^3.0.6
  custom_pop_up_menu: ^1.2.3+1
  open_file: ^3.2.1
  photo_view: ^0.13.0

  cpp_native:
    git:
      url: https://gitlab.upstorage.net/us-core/cpp_native.git
  event_bus: ^2.0.0
  

dev_dependencies:
  injectable_generator:
  build_runner: ^2.1.7
  hive_generator: ^1.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/auth/
    - assets/home_page/
    - assets/file_page/
    - assets/test_img/
    - assets/finance_page/
    - assets/file_page/file_options/
    - assets/file_icons/
    - assets/options/

  fonts:
    - family: Noto Sans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
    - family: Noto Sans Bold
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
flutter_intl:
  enabled: true
