name: upstorage_desktop
description: StorageUp

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  vector_math: any
  dbcrypt: ^2.0.0
  filesystem_picker: ^1.0.3
  tree_view: ^0.0.6
  cupertino_icons: ^1.0.4
  intl: ^0.17.0
  adaptive_theme: ^2.3.1
  flutter_svg: ^1.0.3
  flutter_bloc: ^8.0.1
  formz: ^0.4.1
  equatable: ^2.0.3
  flutter_switch: ^0.3.2
  dio: ^4.0.6
  get_it: ^7.2.0
  injectable: ^1.5.3
  persistent_bottom_nav_bar: ^4.0.2
  permission_handler: ^9.2.0
  scrollable_positioned_list: ^0.2.3
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  desktop_window: ^0.4.0
  shared_preferences: ^2.0.13
  shared_preferences_platform_interface: ^2.0.0
  file_picker: ^4.5.1
  image_picker: ^0.8.4+11
  percent_indicator: 4.0.1
  connectivity: ^3.0.6
  custom_pop_up_menu: ^1.2.3+1
  open_file: ^3.2.1
  photo_view: ^0.13.0
  web_socket_channel: ^2.1.0
  event_bus: ^2.0.0

  os_specification:
    git:
      url: ssh://git@gitlab.upstorage.net:2289/a.som/os_specification.git

  cpp_native:
    git:
      url: ssh://git@gitlab.upstorage.net:2289/us-core/cpp_native.git

  file_typification:
    git:
      url: ssh://git@gitlab.upstorage.net:2289/a.som/file_typification.git
  linked_scroll_controller: ^0.2.0
  syncfusion_flutter_sliders: ^20.1.61
  native_context_menu: ^0.2.1+4
  contextmenu: ^3.0.0

dev_dependencies:
  injectable_generator:
  build_runner: ^2.1.8
  hive_generator: ^1.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/auth/
    - assets/home_page/
    - assets/file_page/
    - assets/test_img/
    - assets/finance_page/
    - assets/file_page/file_options/
    - assets/file_icons/
    - assets/options/
    - assets/space_sell/

  fonts:
    - family: Noto Sans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
    - family: Noto Sans Bold
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
flutter_intl:
  enabled: true
